openapi: 3.0.1
info:
  title: Digital signing service
  description: A service providing Kaleidos the functionality for digitally signing
    documents.
  license:
    name: MIT
    url: https://github.com/kanselarij-vlaanderen/digital-signing-service/LICENSE.txt
  version: 1.0.1
externalDocs:
  description: Git Repository
  url: https://github.com/kanselarij-vlaanderen/digital-signing-service
servers:
- url: /
paths:
  /signing-flows/{signflow_id}/pieces:
    get:
      tags:
      - Signing files
      summary: List pieces associated with a sign flow
      operationId: listSignPieces
      parameters:
      - name: signflow_id
        in: path
        description: ID of sign flow
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/JsonApiData'
  /signing-flows/{signflow_id}/signers:
    get:
      tags:
      - File signers
      summary: List signers for a a given signing-flow
      operationId: listFileSigners
      parameters:
      - name: signflow_id
        in: path
        description: ID of sign flow
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/JsonApiData'
    post:
      tags:
      - File signers
      summary: Add signers for a a given signing-flow
      operationId: addFileSigners
      parameters:
      - name: signflow_id
        in: path
        description: ID of sign flow
        required: true
        schema:
          type: string
          format: uuid
      responses:
        202:
          description: successful operation
          content: {}
  /signing-flows/{signflow_id}/upload-document-to-signinghub:
    post:
      tags:
      - Upload to SigningHub
      summary: Upload documents associated to the Signing-flow to SigningHub and assign Signers that have already been assigned within Kaleidos too.
      operationId: startSigning
      parameters:
      - name: signflow_id
        in: path
        description: ID of sign flow
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Sucessfully sent out signing-flow
components:
  schemas:
    JsonApiResourceIdentification:
      type: object
      properties:
        type:
          type: string
          enum:
          - pieces
          - mandatees
        id:
          type: string
          format: uuid
    JsonApiData:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/JsonApiResourceIdentification'
