PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948 # kanselarij
# http://themis.vlaanderen.be/id/gebruiker/7a992b2f-a437-4919-8965-25b3d7942f93 # Minister

# regular user accounts are in http://mu.semte.ch/graphs/system/users
# mock-login users are in http://mu.semte.ch/graphs/public

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX person: <http://www.w3.org/ns/person#>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948> foaf:mbox ?mail .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://themis.vlaanderen.be/id/gebruiker/10afadbc-6d4c-474e-a1e5-3f8e1af99948> foaf:mbox <mailto:michael.dierick@redpencil.io> .
  }
}
