PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX sign: <http://mu.semte.ch/vocabularies/ext/handteken/>
PREFIX sh: <http://mu.semte.ch/vocabularies/ext/signinghub/>

INSERT {
    GRAPH ?graph {
        ?preparation_activity sign:voorbereidingVindtPlaatsTijdens ?sign_subcase .
        ?preparation_activity a sign:Voorbereidingsactiviteit ;
            mu:uuid ?preparation_activity_id .
        ?preparation_activity sign:voorbereidingGenereert ?sh_document .
        ?sh_document a sh:Document ;
            sh:packageId ?sh_package_id ;
            sh:documentId ?sh_document_id ;
            prov:hadPrimarySource ?piece .
    }
} WHERE {
    GRAPH ?graph {
        ?signflow a sign:Handtekenaangelegenheid ;
            sign:doorlooptHandtekening ?sign_subcase .
        ?sign_subcase a sign:HandtekenProcedurestap .
    }

    VALUES ?signflow { <http://mu.semte.ch/placeholders/signflow> }
    VALUES ?preparation_activity { <http://mu.semte.ch/placeholders/preparation_activity> }
    VALUES ?preparation_activity_id { <http://mu.semte.ch/placeholders/preparation_activity_id> }
    VALUES ?piece { <http://mu.semte.ch/placeholders/piece> }
    VALUES ?sh_document { <http://mu.semte.ch/placeholders/sh_document> }
    VALUES ?sh_document_id { <http://mu.semte.ch/placeholders/sh_document_id> }
    VALUES ?sh_package_id { <http://mu.semte.ch/placeholders/sh_package_id> }
}